apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-pda-api-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-pda-api-app
  template:
    metadata:
      labels:
        app: hub-pda-api-app
    spec:
      containers:
      - name: hub-pda-api-app
        image: mmregistry.mmvietnam.com:5000/hub_pda_api:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: mmregistry-secret


