apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub_pda_api-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub_pda_api-app
  template:
    metadata:
      labels:
        app: hub_pda_api-app
    spec:
      containers:
      - name: hub_pda_api-app
        image: mmregistry-uat.mmvietnam.com:5000/my-app:latest
        ports:
        - containerPort: 4201
      imagePullSecrets:
      - name: mmregistry-secret


