apiVersion: v1
kind: Service
metadata:
  name: hub-pda-api-service
  namespace: default  # namespace the same deployement
spec:
  selector:
    app: hub-pda-api-app  #  Pod choose Deployment label
  ports:
    - protocol: TCP
      port: 4201           # Port extenal
      targetPort: 4201    # Port in container
  type: LoadBalancer     # LoadBalancer provide IP address


